# permissions for end users to edit eventjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventjob-editor-role
rules:
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - eventjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - eventjobs/status
  verbs:
  - get
