# permissions for end users to view eventjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventjob-viewer-role
rules:
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - eventjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - eventjobs/status
  verbs:
  - get
